---
# - name: create directory for selenium
#   shell: mkdir -p {{ selenium_dir }} creates={{ selenium_dir }}

- name: create directory for selenium
  file: path={{ selenium_dir }} owner={{ user }} group={{ user }} state=directory

- include: gnome.yml

- include: selenium.yml

- include: testhost.yml

- include: chromedriver.yml
  when: with_chromedriver

- include: phantomjs.yml
  when: with_phantomjs

- include: firefox.yml

- include: chrome.yml

- name: Disable SELINUX
  shell: sed -i "s/^SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config

- name: Allow 4444 through firewall
  command: /usr/bin/firewall-cmd --add-port=4444/tcp --permanent

- name: Reload firewall
  command: /usr/bin/firewall-cmd --reload

- name: create run script
  template:
    src=run.sh
    dest={{ selenium_dir }}
    owner={{ user }} group={{ user }} mode=0755

- name: create run script
  shell: init 5
